select * from FORNECEDOR;

select * from PRODUTO;

select * from PRODUTO_POR_FORNECEDOR;

select * from CLIENTE;

select * from LOCAL;

select * from ESTOQUE;

select * from VENDEDOR;

select * from PRODUTO_POR_VENDEDOR;

select * from ESTOQUE;

select * from PEDIDO;

select * from PRODUTO_POR_PEDIDO;

select * from ENTREGA;

select * from PAGAMENTO;

select * from PAGAMENTO_POR_PEDIDO;

-- SELECIONAR OS PRODUTOS DO FORNECEDOR TRAMONTINA
select * 
  from PRODUTO P, FORNECEDOR F, PRODUTO_POR_FORNECEDOR FP
 where P.ID = FP.PRODUTO_ID 
   and F.ID = FP.FORNECEDOR_ID 
   and F.NOME_FANTASIA  = 'TRAMONTINA'; 

-- SELECIONAR A SOMA DO ESTOQUE DISPONIVEL DE CADA FORNECEDOR
select F.NOME_FANTASIA as FORNECEDOR, sum(QT_DISPONIVEL) as QT_DISPONIVEL 
  from ESTOQUE E, FORNECEDOR F, PRODUTO_POR_FORNECEDOR FP
 where E.PRODUTO_ID = FP.PRODUTO_ID 
   and F.ID = FP.FORNECEDOR_ID 
group by F.NOME_FANTASIA;

-- SELECIONAR O ESTOQUE DISPONIVEL DE CADA PRODDUTO POR VENDEDOR
select V.ID AS CODIGO_VENDEDOR, V.RAZAO_SOCIAL as VENDEDOR, P.ID as CODIGO_PRODUTO, P.DESCRICAO as PRODUTO, E.QT_DISPONIVEL
  from ESTOQUE E, VENDEDOR V, PRODUTO_POR_VENDEDOR PV, PRODUTO P
 where E.PRODUTO_ID = PV.PRODUTO_ID 
   and V.ID = PV.VENDEDOR_ID 
   and PV.PRODUTO_ID = P.ID;
   
-- SELECIONAR AS VENDAS ENTREGUES POR CLIENTES, ORDENANDO DO MAIOR VALOR PARA O MENOR
select P.ID, concat (C.NOME, ' ', C.NOME_MEIO, ' ', C.NOME_FINAL) as NOME, format(P.VALOR_TOTAL, 2, 'de_DE') as VALOR_TOTAL, E.STATUS_ENTREGA
  from PEDIDO P, CLIENTE C, ENTREGA E 
 where P.CLIENTE_ID = C.ID
   and E.PEDIDO_ID = P.ID
   and E.STATUS_ENTREGA = 'ENTREGUE'
 order by P.VALOR_TOTAL desc;
 
 -- SELECIONAR AS VENDAS PAGAS POR CARTÃO DE CRÉDITO (NÃO SELECIONAR VENDAS CANCELADAS)
 select P.ID, concat (C.NOME, ' ', C.NOME_MEIO, ' ', C.NOME_FINAL) as NOME, format(P.VALOR_TOTAL, 2, 'de_DE') as VALOR_TOTAL, PG.TIPO_DE_PAGAMENTO, P.STATUS as STATUS_PEDIDO
  from PEDIDO P, CLIENTE C, PAGAMENTO PG, PAGAMENTO_POR_PEDIDO PP 
 where P.CLIENTE_ID = C.ID
   and PP.PEDIDO_ID = P.ID
   and PP.PAGAMENTO_ID = PG.ID
   and PG.TIPO_DE_PAGAMENTO = 'CARTAO'
   and P.STATUS <> 'CANCELADO';
 
  -- SELECIONAR O VALOR TOTAL DE VENDAS CANCELADAS
 select P.STATUS, format(sum(P.VALOR_TOTAL), 2, 'de_DE') as VALOR_TOTAL
  from PEDIDO P
 where P.STATUS = 'CANCELADO';
 
   -- SELECIONAR OS PRODUTOS QUE NAO FORAM VENDIDOS
   select P.*
     from PRODUTO P
     where P.ID not in ( select PP.PRODUTO_ID from PRODUTO_POR_PEDIDO PP );

-- SELECIONAR AS VENDAS POR FORNECEDOR
 select F.NOME_FANTASIA, format(sum(PP.VALOR_TOTAL), 2, 'de_DE') as VALOR_TOTAL
  from PRODUTO_POR_PEDIDO PP, FORNECEDOR F, PRODUTO_POR_FORNECEDOR PF, PEDIDO P
 where PP.PRODUTO_ID = PF.PRODUTO_ID
   and PF.FORNECEDOR_ID = F.ID
   and PP.PEDIDO_ID = P.ID
   and P.STATUS <> 'CANCELADO'
 group by F.NOME_FANTASIA;
 
 -- SELECIONAR AS VENDAS POR FORNECEDOR MAIOR QUE 1000,00
 select F.NOME_FANTASIA, format(sum(PP.VALOR_TOTAL), 2, 'de_DE') as VALOR_TOTAL
  from PRODUTO_POR_PEDIDO PP, FORNECEDOR F, PRODUTO_POR_FORNECEDOR PF, PEDIDO P
 where PP.PRODUTO_ID = PF.PRODUTO_ID
   and PF.FORNECEDOR_ID = F.ID
   and PP.PEDIDO_ID = P.ID
   and P.STATUS <> 'CANCELADO'
 group by F.NOME_FANTASIA
 having sum(PP.VALOR_TOTAL) > 1000.00;
 
 -- SELECIONAR TOTAL DE QUANTIDADE VENDIDA POR VENDEDOR
 select V.RAZAO_SOCIAL, sum(PP.QUANTIDADE) as QTDE_VENDIDA
  from PRODUTO_POR_PEDIDO PP, VENDEDOR V, PRODUTO_POR_VENDEDOR PV, PEDIDO P
 where PP.PRODUTO_ID = PV.PRODUTO_ID
   and PV.VENDEDOR_ID = V.ID
   and PP.PEDIDO_ID = P.ID
   and P.STATUS <> 'CANCELADO'
 group by V.RAZAO_SOCIAL;
 
 -- SELECIONAR APENAS O ESTOQUE DOS PRODUTOS QUE JA FORAM VENDIDOS POR VENDEDOR 
 select V.RAZAO_SOCIAL as VENDEDOR, P.DESCRICAO as PRODUTO, sum(E.QT_DISPONIVEL) as QT_ESTOQUE_DISPONIVEL
   from ESTOQUE E, PRODUTO_POR_VENDEDOR PV, VENDEDOR V, PRODUTO P
  where E.PRODUTO_ID = P.ID
    and PV.PRODUTO_ID = P.ID
    and PV.VENDEDOR_ID = V.ID
    and P.ID in ( select PP.PRODUTO_ID 
                    from PRODUTO_POR_PEDIDO PP, PEDIDO PD
				   where PP.PEDIDO_ID = PD.ID
                     and PD.STATUS <> 'CANCELADO' )
  group by V.RAZAO_SOCIAL, P.DESCRICAO;
    